### PR TITLE
Fix unit test crashes and make them more robust

### LINKED ISSUE #42: Test failure with key4hep nightlies
See discussion in #23

### PR DESCRIPTION
**Pull request by tmadlener**
BEGINRELEASENOTES
- Only create `RecoParticleRef` objects if there is a valid reco particle to point to, to avoid possible nullptr access when reading the created files.
- Make the kinematic matching more robust and allow for a less strict second attempt If a strict kinematic matching (dropping the energy from matching) is not possible the first time.
- Make the integration tests that compare the original delphes output to the converted output less dependent on an specific random seed by seeding each test run with random random seeds, but record them so that it becomes possible to reproduce a failure with them.
  
ENDRELEASENOTES

Fixes #42 

Even with the relaxed matching there are still cases where no valid reco particle can be found. For me locally they seem to happen in around 1 of roughly 10k events.
- [ ] Find out why this happens and try to fix it, such that the tests can be run reliably.

### CODE REVIEW

**Comment by tmadlener** [comment]
It seems github actions are way more efficient in finding pathological cases than I am locally ;)

**Comment by tmadlener** [comment]
Now also the github action workflows seem to be at the "1 in 10k events" frequency of problems during the conversion.

All of the problems that I have observed seem to be related to cases where there is no matching reconstructed particle for a muon coming from delphes. I had a look into a few of these cases and this does not seem to be related to the problems with getting a matching reconstructed particle, but rather getting a candidate for matching at all. I.e. with the default output configuration we are getting muon candidates from delphes that are not in the `EFlowTrack`, `EFlowPhoton` or `EFlowNeutralHadron` branches. Looking at the attached data flow diagram it is not yet clear to me how this happens.

data_flow

File: converter/src/delphesHelpers.h [hunk 1]
```diff
@@ -28,18 +29,37 @@ inline LorentzVectorT getP4(const T& particle) {
...
- * energy and all momentum components. The energy requirement can be dropped on
- * demand.
+ * Combination of a relative and absolute comparison. The absolute comparison
+ * should take precedence if the compared values are small, where relative
+ * differences can become very large. The definition of "small" depends on the
+ * ratio of relEps / absEps. E.g. for equal values everything for |a|, |b| < 1
+ * is considered small. In general max(|a|, |b|) < absEps / relEps defines where
+ * "small" begins for inputs a and b
+ */
+  bool cmp_float(float a, float b, float absEps=1e-6, float relEps=1e-6) {
```
Comment (vvolkl) [inline converter/src/delphesHelpers.h:41]: In some float comparisons (for example numpy.isclose) the abolute and relative tolerance are added and then compared to the difference. I think this is fine too, though.

**Comment by vvolkl** [comment]
Thanks Thomas, this problem is not yet clear to me either. I think it'll be a good opportunity to review the conversion code and the corresponding docs. In any case it's nice the tests work for the nightlies now.

File: converter/src/delphesHelpers.h (hunk 1 above)
Comment (tmadlener) [reply converter/src/delphesHelpers.h:41]: That is interesting to know, I actually haven't checked the numpy implementation. In any case, I think this should be a much more robust and valid float comparison implementation than the previous one, which was failing quite often, especially for small numbers.
