### PR TITLE
Fix flaky tests by disregarding order of mc-reco links

### LINKED ISSUE #129: DelphesRootReader_ee_91gev test failing
2/7 Test #5: DelphesRootReader_ee_91gev .....................***Failed    8.78 sec

See log files.

### PR DESCRIPTION
**Pull request by tmadlener**
BEGINRELEASENOTES
- Make MC-Reco links comparisons pass even if they are not the same order in EDM4hep and Delphes as long as all the links are present.

ENDRELEASENOTES

~- [ ] Needs https://github.com/key4hep/key4hep-actions/pull/7~

As already stated in the inline comment: Delphes seems to write these in different orders even with the same random seed. It seems to only happen during writing of the Delphes file, as the EDM4hep files that come out of the converter are the same. I have done a `diff <(podio-dump -d -e <offending-event> <run_1.root>) <(podio-dump -d -e <offending-event> <run-2.root>)` and that yields no differences in the files apart from the obviously different file names.

Given all that, I think this is the most reasonable fix we can make.

Fixes #129

### CODE REVIEW

File: tests/src/compare_delphes_converter_outputs.cpp [hunk 1]
```diff
@@ -98,14 +98,26 @@ template <typename DelphesT> std::vector<GenParticle*> getAssociatedMCParticles(
...
+                        const edm4hep::RecoMCParticleLinkCollection& associations) {
+  auto delphesGenParticles = getAssociatedMCParticles(delphesCand);
+  auto edm4hepMCParticles  = getAssociatedMCParticles(edm4hepCand, associations);
 
   if (delphesGenParticles.size() != edm4hepMCParticles.size()) {
     return false;
   }
 
+  // In some cases the order of the vectors is not exactly the same, because
+  // Delphes(!) seems to write them in a different order from time to time even
```
Comment (andresailer) [inline tests/src/compare_delphes_converter_outputs.cpp:110]: Does that mean delphes uses pointers (or similar) for map keys and that is affected by memory randomization?

**Comment by tmadlener** [comment]
I didn't observe any failures locally with this in 30 repetitions. Given previous experience in #129 I would have expected around 10, so I think this at least fixes the observed failure.

**Comment by tmadlener** [comment]
Merging this, then rebasing #128 to get a tag done for the next Key4hep release, unless someone complains in the next hour.

**Review by andresailer — APPROVED** [review]
