### PR TITLE
Fix HepMC Reader

### LINKED ISSUE #34: DelphesHepMC_EDM4HEP aborts reading after one entry
Using a hepmc file generated with k4gen. The upstream DelphesHepMC command can read it fine.

### LINKED ISSUE #102: HepMC to EDM4Hep is broken
Dear all,

I am looking for a way to run DelphesEDM4Hep with a HepMC file as input and EDM4Hep file as output. My problem is when I run the executable DelphesHepMC_EDM4HEP then it overwrites the output_config_file and I get this error:
```
** ERROR: can't read configuration file edm4hep_output_config.tcl
```
I have no problem with other executables. Only with this one. 

The command I use is:
```
DelphesHepMC_EDM4HEP card_IDEA.tcl edm4hep_output_config.tcl stopsDelphes_edm4hep.root  ee_stops.hepmc
```

### PR DESCRIPTION
**Pull request by tmadlener**
BEGINRELEASENOTES
- Fix the HepMC reader that erroneously overwrote one of its input arguments. Fixes #102 
- Fix stopping of HepMC reader after reading only one event. Fixes #34 
- Fix leaking of the internal `DelphesHepMC2Reader` by using a `unique_ptr`.

ENDRELEASENOTES

### CODE REVIEW

File: standalone/src/DelphesHepMCReader.h [hunk 1]
```diff
@@ -95,39 +95,42 @@ class DelphesHepMCInputReader : public DelphesInputReader {
...
     m_eventCounter++;
-    return m_finished;
+    return finished;
   }
 
-  bool finished() const override { return m_finished; };
+  // For the HepMC reader there is no real way of determining on whether it is
+  // finished or not, so we return always false here, because readEvent will
+  // report on whether it wsa possible to read or not
+  bool finished() const override { return false; };
```
Comment (jmcarcell) [inline standalone/src/DelphesHepMCReader.h:114]: Why should this always return false?

File: standalone/src/DelphesHepMCReader.h [hunk 2]
```diff
@@ -95,39 +95,42 @@ class DelphesHepMCInputReader : public DelphesInputReader {
...
     m_treeWriter->Clear();
     m_readStopWatch.Start();
-    auto factory = modularDelphes->GetFactory();
+    auto factory  = modularDelphes->GetFactory();
+    bool finished = false;
     do {
-      m_finished = m_reader->ReadBlock(factory, allParticleOutputArray, stableParticleOutputArray, partonOutputArray);
-    } while (m_finished && !m_reader->EventReady());
+      finished = m_reader->ReadBlock(factory, allParticleOutputArray, stableParticleOutputArray, partonOutputArray);
+    } while (finished && !m_reader->EventReady());
```
Comment (jmcarcell) [inline standalone/src/DelphesHepMCReader.h:102]: What about changing `finished` to another name since it just indicates whether the read was good or not, maybe something like:

```
bool goodRead;
while (goodRead = m_reader->ReadBlock(factory, allParticleOutputArray, stableParticleOutputArray, partonOutputArray) && !m_reader->EventReady()) {}
```

**Review by jmcarcell — APPROVED** [review]
Looks good, changes fix the problems and the output file seems to be fine.
